<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)/props/windows.build.props" />
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="splash.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Brows.Commander.Windows\Brows.Commander.Windows.csproj" />
  </ItemGroup>
</Project>
