<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>99.98.97.101</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\samples\Brows.IPC.Sample.Host\Brows.IPC.Sample.Host.csproj" />
    <ProjectReference Include="..\..\source\Brows.IPC.Host\Brows.IPC.Host.csproj" />
    <ProjectReference Include="..\..\source\Brows.Framework.Testing\Brows.Framework.Testing.csproj" />
  </ItemGroup>
</Project>
