namespace Brows.Runtime.Win32 {
    internal enum SPACTION {
        SPACTION_NONE = 0,
        SPACTION_MOVING,
        SPACTION_COPYING,
        SPACTION_RECYCLING,
        SPACTION_APPLYINGATTRIBS,
        SPACTION_DOWNLOADING,
        SPACTION_SEARCHING_INTERNET,
        SPACTION_CALCULATING,
        SPACTION_UPLOADING,
        SPACTION_SEARCHING_FILES,
        SPACTION_DELETING,
        SPACTION_RENAMING,
        SPACTION_FORMATTING,
        SPACTION_COPY_MOVING
    }
}
