theme: jekyll-theme-minimal

title: Brows
logo: logo.png
description: Brows is a Windows file manager for power users.

show_downloads: true

permalink: /post/:title/
markdown: kramdown
date_format: "%b %-d, %Y"

collections:
  docs:
    output: true
    permalink: /:collection/:path
