<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Moq"/>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>
</Project>