<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\samples\Brows.CLI.Sample\Brows.CLI.Sample.csproj" />
    <ProjectReference Include="..\..\source\Brows.Framework.Testing\Brows.Framework.Testing.csproj" />
  </ItemGroup>
</Project>
