using System.Collections.Generic;

namespace Domore.Runtime.Win32.PropSys {
    internal static class LegacyPropertyName {
        public static readonly IReadOnlyDictionary<string, string> Lookup = new Dictionary<string, string> {
            { "Access", "System.DateAccessed" },
            { "Album", "System.Music.AlbumTitle" },
            { "AllocSize", "System.FileAllocationSize" },
            { "Aperture", "System.Photo.Aperture" },
            { "Artist", "System.Music.Artist" },
            { "Attrib", "System.FileAttributes" },
            { "Attributes", "System.FileAttributes" },
            { "AttributesDescription", "System.FileAttributesDisplay" },
            { "Audio Format", "System.Audio.Format" },
            { "Audio Sample Size", "System.Audio.SampleSize" },
            { "BitDepth", "System.Image.BitDepth" },
            { "Bitrate", "System.Audio.EncodingBitrate" },
            { "CameraModel", "System.Photo.CameraModel" },
            { "Capacity", "System.Capacity" },
            { "Channels", "System.Audio.ChannelCount" },
            { "ColorSpace", "System.Image.ColorSpace" },
            { "Company", "System.Company" },
            { "Compression", "System.Video.Compression" },
            { "Compression", "System.Video.Compression" },
            { "Copyright", "System.Copyright" },
            { "Copyright", "System.Copyright" },
            { "Copyright", "System.Image.Copyright" },
            { "Create", "System.DateCreated" },
            { "CSCStatus", "System.OfflineStatus" },
            { "Data Rate", "System.Video.EncodingBitrate" },
            { "DateDeleted", "System.Recycle.DateDeleted" },
            { "DeletedFrom", "System.Recycle.DeletedFrom" },
            { "Dimensions", "System.Image.Dimensions" },
            { "Directory", "System.ItemFolderNameDisplay" },
            { "Distance", "System.Photo.SubjectDistance" },
            { "DocAppName", "System.ApplicationName" },
            { "DocAuthor", "System.Author" },
            { "DocByteCount", "System.Document.ByteCount" },
            { "DocCategory", "System.Category" },
            { "DocCharCount", "System.Document.CharacterCount" },
            { "DocComments", "System.Comment" },
            { "DocCompany", "System.Company" },
            { "DocCreatedTm", "System.Document.DateCreated" },
            { "DocEditTime", "System.Document.TotalEditingTime" },
            { "DocHiddenCount", "System.Document.HiddenSlideCount" },
            { "DocKeywords", "System.Keywords" },
            { "DocLastAuthor", "System.Document.LastAuthor" },
            { "DocLastPrinted", "System.Document.DatePrinted" },
            { "DocLastSavedTm", "System.Document.DateSaved" },
            { "DocLineCount", "System.Document.LineCount" },
            { "DocManager", "System.Document.Manager" },
            { "DocNoteCount", "System.Document.NoteCount" },
            { "DocPageCount", "System.Document.PageCount" },
            { "DocParaCount", "System.Document.ParagraphCount" },
            { "DocPresentationTarget", "System.Document.PresentationFormat" },
            { "DocRevNumber", "System.Document.RevisionNumber" },
            { "DocSlideCount", "System.Document.SlideCount" },
            { "DocSubject", "System.Subject" },
            { "DocTemplate", "System.Document.Template" },
            { "DocTitle", "System.Title" },
            { "DocWordCount", "System.Document.WordCount" },
            { "DRM Description", "System.DRM.Description" },
            { "Duration", "System.Media.Duration" },
            { "EquipMake", "System.Photo.CameraManufacturer" },
            { "ExposureBias", "System.Photo.ExposureBias" },
            { "ExposureProg", "System.Photo.ExposureProgram" },
            { "ExposureTime", "System.Photo.ExposureTime" },
            { "FaxCallerID", "System.Fax.CallerID" },
            { "FaxCSID", "System.Fax.CSID" },
            { "FaxRecipientName", "System.Fax.RecipientName" },
            { "FaxRecipientNumber", "System.Fax.RecipientNumber" },
            { "FaxRouting", "System.Fax.Routing" },
            { "FaxSenderName", "System.Fax.SenderName" },
            { "FaxTime", "System.Fax.Time" },
            { "FaxTSID", "System.Fax.TSID" },
            { "FileDescription", "System.FileDescription" },
            { "FileSystem", "System.Volume.FileSystem" },
            { "FileType", "System.Image.FileType" },
            { "FileVersion", "System.FileVersion" },
            { "Flash", "System.Photo.Flash" },
            { "FlashEnergy", "System.Photo.FlashEnergy" },
            { "FNumber", "System.Photo.FNumber" },
            { "FocalLength", "System.Photo.FocalLength" },
            { "Frame Rate", "System.Video.FrameRate" },
            { "FrameCount", "System.Media.FrameCount" },
            { "FreeSpace", "System.FreeSpace" },
            { "Genre", "System.Music.Genre" },
            { "ImageX", "System.Image.HorizontalSize" },
            { "ImageY", "System.Image.VerticalSize" },
            { "ISOSpeed", "System.Photo.ISOSpeed" },
            { "LightSource", "System.Photo.LightSource" },
            { "LinksUpToDate", "System.Document.LinksDirty" },
            { "LinkTarget", "System.Link.TargetParsingPath" },
            { "Lyrics", "System.Music.Lyrics" },
            { "Manager", "System.Document.Manager" },
            { "MeteringMode", "System.Photo.MeteringMode" },
            { "MMClipCount", "System.Document.MultimediaClipCount" },
            { "Name", "System.ItemNameDisplay" },
            { "Owner", "System.FileOwner" },
            { "Play Count", "System.DRM.PlayCount" },
            { "Play Expires", "System.DRM.DatePlayExpires" },
            { "Play Starts", "System.DRM.DatePlayStarts" },
            { "PresentationTarget", "System.Document.PresentationFormat" },
            { "ProductName", "System.Software.ProductName" },
            { "ProductVersion", "System.Software.ProductVersion" },
            { "Project", "System.Media.Project" },
            { "Protected", "System.DRM.IsProtected" },
            { "Rank", "System.Search.Rank" },
            { "Rating", "System.Rating" },
            { "ResolutionX", "System.Image.HorizontalResolution" },
            { "ResolutionY", "System.Image.VerticalResolution" },
            { "Sample Rate", "System.Audio.SampleRate" },
            { "Scale", "System.Document.Scale" },
            { "ShutterSpeed", "System.Photo.ShutterSpeed" },
            { "Size", "System.Size" },
            { "Software", "System.SoftwareUsed" },
            { "Status", "System.Media.Status" },
            { "Status", "System.Status" },
            { "Stream Name", "System.Video.StreamName" },
            { "SyncCopyIn", "System.Sync.CopyIn" },
            { "Track", "System.Music.TrackNumber" },
            { "Type", "System.ItemTypeText" },
            { "Video Sample Size", "System.Video.SampleSize" },
            { "WhenTaken", "System.Photo.DateTaken" },
            { "Write", "System.DateModified" },
            { "Year", "System.Media.Year" },
        };
    }
}
