<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <OutputPath>$(SolutionDir)\out\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\source\Brows.Abstractions.IO\Brows.Abstractions.IO.csproj" />
    <ProjectReference Include="..\Brows.App.Windows\Brows.App.Windows.csproj" />
    <ProjectReference Include="..\Brows.Commander.Windows\Brows.Commander.Windows.csproj" />
    <ProjectReference Include="..\Brows.Commander\Brows.Commander.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="brows.config\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Remove="brows.config\default\ftp.conf.default" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Domore.Logs.Conf" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="brows.config\default\ftp.conf.default">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
  <Target Name="GetTargetPath" Returns="@(Brows_SetupOutputPath)">
    <ItemGroup Condition="'$(OutputType)' == 'Library'">
      <Brows_SetupOutputPath Include="$(MSBuildProjectDirectory)\$(OutputPath)\$(Brows_SetupTargetFramework)\$(AssemblyName).dll" />
    </ItemGroup>
    <ItemGroup Condition="'$(OutputType)' == 'Exe'">
      <Brows_SetupOutputPath Include="$(MSBuildProjectDirectory)\$(OutputPath)\$(Brows_SetupTargetFramework)\$(AssemblyName).exe" />
    </ItemGroup>
    <ItemGroup Condition="'$(OutputType)' == 'WinExe'">
      <Brows_SetupOutputPath Include="$(MSBuildProjectDirectory)\$(OutputPath)\$(Brows_SetupTargetFramework)\$(AssemblyName).exe" />
    </ItemGroup>
  </Target>
</Project>